// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parcial_2.Dal.Data;

#nullable disable

namespace Parcial_2.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240609005236_Second")]
    partial class Second
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Parcial_2.Dal.Entities.Cancion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DiscoId")
                        .HasColumnType("int");

                    b.Property<int>("TiempoDuracion")
                        .HasColumnType("int");

                    b.Property<string>("TituloCancion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DiscoId");

                    b.ToTable("Canciones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DiscoId = 1,
                            TiempoDuracion = 123,
                            TituloCancion = "Test"
                        },
                        new
                        {
                            Id = 2,
                            DiscoId = 2,
                            TiempoDuracion = 321,
                            TituloCancion = "Test2"
                        },
                        new
                        {
                            Id = 3,
                            DiscoId = 1,
                            TiempoDuracion = 180,
                            TituloCancion = "Rockin' Revolution"
                        },
                        new
                        {
                            Id = 4,
                            DiscoId = 1,
                            TiempoDuracion = 240,
                            TituloCancion = "Midnight Rider"
                        },
                        new
                        {
                            Id = 5,
                            DiscoId = 1,
                            TiempoDuracion = 210,
                            TituloCancion = "Guitar Gods"
                        },
                        new
                        {
                            Id = 6,
                            DiscoId = 2,
                            TiempoDuracion = 300,
                            TituloCancion = "Echoes of Time"
                        },
                        new
                        {
                            Id = 7,
                            DiscoId = 2,
                            TiempoDuracion = 280,
                            TituloCancion = "Rolling Thunder"
                        },
                        new
                        {
                            Id = 8,
                            DiscoId = 2,
                            TiempoDuracion = 420,
                            TituloCancion = "Stairway to Heaven"
                        },
                        new
                        {
                            Id = 9,
                            DiscoId = 3,
                            TiempoDuracion = 320,
                            TituloCancion = "Starlight Symphony"
                        },
                        new
                        {
                            Id = 10,
                            DiscoId = 3,
                            TiempoDuracion = 280,
                            TituloCancion = "Galactic Groove"
                        },
                        new
                        {
                            Id = 11,
                            DiscoId = 3,
                            TiempoDuracion = 240,
                            TituloCancion = "Celestial Serenade"
                        },
                        new
                        {
                            Id = 12,
                            DiscoId = 4,
                            TiempoDuracion = 260,
                            TituloCancion = "Moonshine Melodies"
                        },
                        new
                        {
                            Id = 13,
                            DiscoId = 4,
                            TiempoDuracion = 290,
                            TituloCancion = "Bluesy Breeze"
                        },
                        new
                        {
                            Id = 14,
                            DiscoId = 4,
                            TiempoDuracion = 220,
                            TituloCancion = "Grit and Grace"
                        },
                        new
                        {
                            Id = 15,
                            DiscoId = 5,
                            TiempoDuracion = 330,
                            TituloCancion = "Wildfire Dreams"
                        },
                        new
                        {
                            Id = 16,
                            DiscoId = 5,
                            TiempoDuracion = 270,
                            TituloCancion = "Burning Bridges"
                        },
                        new
                        {
                            Id = 17,
                            DiscoId = 5,
                            TiempoDuracion = 310,
                            TituloCancion = "Fevered Fantasies"
                        },
                        new
                        {
                            Id = 18,
                            DiscoId = 6,
                            TiempoDuracion = 290,
                            TituloCancion = "Electric Elegy"
                        },
                        new
                        {
                            Id = 19,
                            DiscoId = 6,
                            TiempoDuracion = 250,
                            TituloCancion = "Cosmic Cadence"
                        },
                        new
                        {
                            Id = 20,
                            DiscoId = 6,
                            TiempoDuracion = 280,
                            TituloCancion = "Nebula Nocturne"
                        },
                        new
                        {
                            Id = 21,
                            DiscoId = 7,
                            TiempoDuracion = 240,
                            TituloCancion = "Silver Shadows"
                        },
                        new
                        {
                            Id = 22,
                            DiscoId = 7,
                            TiempoDuracion = 270,
                            TituloCancion = "Shadow Shuffle"
                        },
                        new
                        {
                            Id = 23,
                            DiscoId = 7,
                            TiempoDuracion = 310,
                            TituloCancion = "Bluesy Ballad"
                        },
                        new
                        {
                            Id = 24,
                            DiscoId = 8,
                            TiempoDuracion = 330,
                            TituloCancion = "Sunset Serenade"
                        },
                        new
                        {
                            Id = 25,
                            DiscoId = 8,
                            TiempoDuracion = 270,
                            TituloCancion = "Psychedelic Sunset"
                        },
                        new
                        {
                            Id = 26,
                            DiscoId = 8,
                            TiempoDuracion = 310,
                            TituloCancion = "Twilight Tango"
                        },
                        new
                        {
                            Id = 27,
                            DiscoId = 9,
                            TiempoDuracion = 240,
                            TituloCancion = "Thunder Road"
                        },
                        new
                        {
                            Id = 28,
                            DiscoId = 9,
                            TiempoDuracion = 270,
                            TituloCancion = "Electric Storm"
                        },
                        new
                        {
                            Id = 29,
                            DiscoId = 9,
                            TiempoDuracion = 310,
                            TituloCancion = "Hard Rockin' Highway"
                        },
                        new
                        {
                            Id = 30,
                            DiscoId = 10,
                            TiempoDuracion = 330,
                            TituloCancion = "Fire and Fury"
                        },
                        new
                        {
                            Id = 31,
                            DiscoId = 10,
                            TiempoDuracion = 270,
                            TituloCancion = "Inferno Jam"
                        },
                        new
                        {
                            Id = 32,
                            DiscoId = 10,
                            TiempoDuracion = 310,
                            TituloCancion = "Rock 'n' Roll Riot"
                        });
                });

            modelBuilder.Entity("Parcial_2.Dal.Entities.Disco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Banda")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaLanzamiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnidadesVendidas")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Discos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Banda = "Test",
                            FechaLanzamiento = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Test",
                            Nombre = "Test",
                            SKU = "Test",
                            UnidadesVendidas = 1
                        },
                        new
                        {
                            Id = 2,
                            Banda = "Test2",
                            FechaLanzamiento = new DateTime(1999, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Test2",
                            Nombre = "Test2",
                            SKU = "Test2",
                            UnidadesVendidas = 2
                        },
                        new
                        {
                            Id = 3,
                            Banda = "The Midnight Riders",
                            FechaLanzamiento = new DateTime(1975, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Rock",
                            Nombre = "Revolution Road",
                            SKU = "RR1975",
                            UnidadesVendidas = 500000
                        },
                        new
                        {
                            Id = 4,
                            Banda = "The Rolling Thunder",
                            FechaLanzamiento = new DateTime(1969, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Classic Rock",
                            Nombre = "Echoes of Time",
                            SKU = "EOT1969",
                            UnidadesVendidas = 1000000
                        },
                        new
                        {
                            Id = 5,
                            Banda = "The Phoenix Effect",
                            FechaLanzamiento = new DateTime(1982, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Rock",
                            Nombre = "Wildfire Dreams",
                            SKU = "WD1982",
                            UnidadesVendidas = 750000
                        },
                        new
                        {
                            Id = 6,
                            Banda = "The Cosmic Cadence",
                            FechaLanzamiento = new DateTime(1978, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Progressive Rock",
                            Nombre = "Starlight Symphony",
                            SKU = "SS1978",
                            UnidadesVendidas = 300000
                        },
                        new
                        {
                            Id = 7,
                            Banda = "The Silver Shadows",
                            FechaLanzamiento = new DateTime(1972, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Blues Rock",
                            Nombre = "Moonshine Melodies",
                            SKU = "MM1972",
                            UnidadesVendidas = 450000
                        },
                        new
                        {
                            Id = 8,
                            Banda = "The Twilight Riders",
                            FechaLanzamiento = new DateTime(1967, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Psychedelic Rock",
                            Nombre = "Sunset Serenade",
                            SKU = "SS1967",
                            UnidadesVendidas = 700000
                        },
                        new
                        {
                            Id = 9,
                            Banda = "The Electric Storm",
                            FechaLanzamiento = new DateTime(1971, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Hard Rock",
                            Nombre = "Thunder Road",
                            SKU = "TR1971",
                            UnidadesVendidas = 850000
                        },
                        new
                        {
                            Id = 10,
                            Banda = "The Inferno Band",
                            FechaLanzamiento = new DateTime(1965, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Rock 'n' Roll",
                            Nombre = "Fire and Fury",
                            SKU = "FF1965",
                            UnidadesVendidas = 1200000
                        });
                });

            modelBuilder.Entity("Parcial_2.Dal.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Test@Test.com",
                            Name = "Test",
                            Password = "Test",
                            UserName = "Test"
                        },
                        new
                        {
                            Id = 2,
                            Email = "Test2@Test2.com",
                            Name = "Test2",
                            Password = "Test2",
                            UserName = "Test2"
                        },
                        new
                        {
                            Id = 3,
                            Email = "Test3@Test3.com",
                            Name = "Test3",
                            Password = "string",
                            UserName = "string"
                        },
                        new
                        {
                            Id = 4,
                            Email = "Test4@Test4.com",
                            Name = "Test4",
                            Password = "password",
                            UserName = "user"
                        });
                });

            modelBuilder.Entity("Parcial_2.Dal.Entities.Cancion", b =>
                {
                    b.HasOne("Parcial_2.Dal.Entities.Disco", "Disco")
                        .WithMany("Canciones")
                        .HasForeignKey("DiscoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Disco");
                });

            modelBuilder.Entity("Parcial_2.Dal.Entities.Disco", b =>
                {
                    b.Navigation("Canciones");
                });
#pragma warning restore 612, 618
        }
    }
}
